baseURL = 'https://waterflowers.github.io/'
title = 'Waterflowers Knowledge'
theme = 'LoveIt'
languageCode = 'en'

[params]

  customCSS = ['css/custom.css']

  [params.home.profile]
    enable = true
    title = "Explore · Record · Share"
    subtitle = "A personal knowledge repository"
    avatarURL = "/images/avatar.jpg"

    social = true



  [params.author]
    name = 'WaterFlowers'

  [params.social]
    GitHub = 'WaterFlowers'
    Email = '326238137@qq.com'

[[menu.main]]
  name = 'Posts'
  url = '/posts/'
  weight = 1

[[menu.main]]
  name = 'Tags'
  url = '/tags/'
  weight = 2

[[menu.main]]
  name = 'About'
  url = '/about/'
  weight = 3
