baseURL = 'https://waterflowers.github.io/'
title = 'SpatialLab'   # ← 改了
theme = 'LoveIt'
defaultTheme = "dark"   # ← 加上这一行，默认主题颜色
languageCode = 'en'

[params]
  customCSS = ['css/custom.css']

[params.page]
   maxWidth = "100%"    # 试试这个

[params.header.title]
  name = 'Heng · SpatialLab  𓁈'          # ← 改了
  subtitle = 'HPC · Digital Twin'  # ← 新增，可选

[params.home.profile]
  enable = true
  title = "记录 · 探索  · 分享"   # ← 这是首页头像下方的标题，不是左上角
  subtitle = "HPC · Spatial Computing · RAG · UE"
  avatarURL = "/images/avatar.jpg"
  social = true

[params.home.posts]
    enable = true   # 关闭博客文章列表，首页不显示文章
    paginate = 3   # 显示最近3篇，避免太长

[params.author]
  name = 'WaterFlowers'

[params.social]
  GitHub = 'WaterFlowers'
  Email = '326238137@qq.com'
  LinkedIn = "你的LinkedInID"      # 添加 LinkedIn
  Twitter = "你的TwitterID"        # 添加 Twitter
  GoogleScholar = "你的ID"         # 添加 Google Scholar
  Orcid = "你的ORCID"              # 添加 ORCID
  YouTube = "我的油管"
  QQ = "326238137"

  # 添加不蒜子计数
[params.busuanzi]
  enable = true       # 是否开启
  site_uv = true      # 全站独立访客数
  site_uv_pre = '<i class="fa fa-user"></i>' # 访客数图标
  site_pv = true      # 全站浏览量
  site_pv_pre = '<i class="fa fa-eye"></i>'  # 浏览量图标
  page_pv = true      # 单页浏览量
  page_pv_pre = '<i class="far fa-eye fa-fw"></i>' # 单页浏览量图标

[[menu.main]]
  name = 'Posts'
  url = '/posts/'
  weight = 2

[[menu.main]]
  name = 'Tags'
  url = '/tags/'
  weight = 3

[[menu.main]]
  name = 'Projects'
  url = '/projects/liangjing/'
  weight = 1

[[menu.main]]
  name = 'About'
  url = '/about/'
  weight = 4
  # '关于我' 已删除，避免重复

